site_name: Kubernetes Fundamentals Labs
site_url: https://stevenwadeconsulting.github.io/k8s-fundamentals-labs
repo_name: stevenwadeconsulting/k8s-fundamentals-labs
repo_url: https://github.com/stevenwadeconsulting/k8s-fundamentals-labs
edit_uri: ""
site_dir: public

# Page tree
nav:
  - Home: index.md
  - Labs:
      - 1. Initial Exploration: labs/1-essentials.md
      - 2. Deployments: labs/2-deployments.md
      - 3. DeamonSets: labs/3-daemonsets.md
      - 4. Services: labs/4-services.md
      - 5. Autoscaling: labs/5-autoscaling.md
      - 6. Storage: labs/6-storage.md
      - 7. Network Policies: labs/7-network-policies.md
      - 8. RBAC: labs/8-rbac.md
      - 9. Complete App: labs/9-complete-app.md

# Configuration
theme:
  feaures:
    - tabs
  name: material
  icon:
    logo: material/cloud
  font:
    text: Ubuntu
    code: Ubuntu Mono
  static_templates:
    - 404.html

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
        # - pymdownx.highlight:
      #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/swade1987
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/stevendavidwade/

copyright: Copyright &copy; 2025 Steven Wade Consulting
