site_name: Kubernetes Fundamentals
site_url: https://stevenwadeconsulting.github.io/k8s-fundamentals-labs
repo_name: stevenwadeconsulting/k8s-fundamentals-labs
repo_url: https://github.com/stevenwadeconsulting/k8s-fundamentals-labs
edit_uri: ""
site_dir: public

# Page tree
nav:
  - Home: index.md
  - Accessing Your Cluster: access.md
  - Labs:
      - 1. Initial Exploration: labs/1-essentials.md
      - 2. Deployments: labs/2-deployments.md
      - 3. DeamonSets: labs/3-daemonsets.md
      - 4. Services & Networking: labs/4-services.md
      - 5. Horizontal Pod Autoscaling: labs/5-autoscaling.md
      - 6. Persistent Storage: labs/6-storage.md
      - 7. Network Policies: labs/7-network-policies.md
      - 8. Role-Based Access Control: labs/8-rbac.md
      - 9. Final Exercise (bonus): labs/9-complete-app.md
  - Resources:
    - About Your Instructor: about-instructor.md
    - Provide Feedback: https://forms.gle/HxoVhSZRNk49BweS9

# Configuration
theme:
  language: en
  features:
    - tabs
    - navigation.sections
    - content.code.copy
  name: material
  icon:
    logo: material/cloud
    repo: fontawesome/brands/github
  font:
    text: Ubuntu
    code: Ubuntu Mono

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/swade1987
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/stevendavidwade/

copyright: Copyright &copy; 2025 Steven Wade Consulting
