apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage-xfs-retain
  resources:
    requests:
      storage: 1Gi
