apiVersion: v1
kind: Pod
metadata:
  name: resize-check-pod
spec:
  containers:
    - name: volume-check
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: resized-volume
  volumes:
    - name: resized-volume
      persistentVolumeClaim:
        claimName: my-first-pvc
