apiVersion: v1
kind: Pod
metadata:
  name: retain-pod
spec:
  containers:
    - name: retain-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: retain-volume
  volumes:
    - name: retain-volume
      persistentVolumeClaim:
        claimName: retain-pvc
