apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hashicorp/http-echo:latest
          args:
            - "-text=Frontend service connecting to backend at: \${BACKEND_URL}"
          ports:
            - containerPort: 5678
          env:
            - name: BACKEND_URL
              value: "http://backend-service"
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
            requests:
              memory: "32Mi"
              cpu: "50m"
