apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-label-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-label
      tier: backend
      version: v1
  template:
    metadata:
      labels:
        app: multi-label
        tier: backend
        version: v1
    spec:
      containers:
        - name: http-echo
          image: hashicorp/http-echo:latest
          args:
            - "-text=Multi-label app v1"
          ports:
            - containerPort: 5678
