apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  app.properties: |
    environment=production
    logging.level=info
  index.html: |
    <html>
    <body>
    <h1>Hello from Kubernetes ConfigMap!</h1>
    <p>This content is dynamically loaded from a ConfigMap.</p>
    </body>
    </html>
