apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final-app
data:
  app.properties: |
    title=Kubernetes Workshop Demo
    color=blue
    message=Hello from ConfigMap!
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      location /api {
        proxy_pass http://backend-service;
      }
    }
