apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: app-sa
      containers:
        - name: api
          image: hashicorp/http-echo:latest
          args:
            - "-text=API Response: Connected to database at \${DB_HOST}, API Key: \${API_KEY}"
          ports:
            - containerPort: 5678
          env:
            - name: DB_HOST
              value: mysql
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: api-key
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "150m"
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            periodSeconds: 10
