apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: app-sa
      containers:
        - name: api
          image: hashicorp/http-echo:latest
          args:
            - "-text={\"result\":\"API Response: Connected to database at mysql\"}"
          ports:
            - containerPort: 5678
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
            requests:
              memory: "32Mi"
              cpu: "20m"
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            periodSeconds: 10
