apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  labels:
    app: log-collector
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
        - name: collector
          image: busybox:1.28
          command:
            - /bin/sh
            - -c
            - >
              while true; do
                echo "Collecting logs from node $(hostname) at $(date)"
                # In a real scenario, we'd collect logs here
                sleep 60
              done
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "50m"
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
