apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-sa-view
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: rbac-test
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
