apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rbac-test-app
  template:
    metadata:
      labels:
        app: rbac-test-app
    spec:
      serviceAccountName: app-sa
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
