apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
spec:
  serviceAccountName: app-sa
  containers:
    - name: kubectl-container
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
