apiVersion: v1
kind: Pod
metadata:
  name: troubleshoot-pod
spec:
  serviceAccountName: troubleshoot-sa
  containers:
    - name: kubectl-container
      image: bitnami/kubectl:latest
      command: ["sleep", "3600"]
