name: docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml

permissions:
  contents: read

concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: setup python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.x

      - name: setup cache
        run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: handle cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: install mkdocs material
        run: |
          pip install mkdocs-material

      - name: build mkdocs
        run: |
          mkdocs build

      - name: upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_ENDPOINT_URL: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          aws s3 sync public/ s3://workshop-platformfix-com/k8s/ --delete
